# Generated by Django 3.2.9 on 2022-08-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(max_length=255, upload_to='')),
                ('location', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
            ],
        ),
    ]
