# Generated by Django 3.2.9 on 2022-08-04 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='Charity',
        ),
    ]
