# Generated by Django 3.2.9 on 2022-08-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_hotel_charity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charity',
            old_name='telephone',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='image',
        ),
        migrations.AddField(
            model_name='charity',
            name='phone',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
