# Generated by Django 3.2.9 on 2022-08-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220804_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
            ],
        ),
    ]
