# Generated by Django 3.2.9 on 2022-09-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_churchdonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchdonation',
            name='paymentway',
            field=models.CharField(default=11, max_length=255),
            preserve_default=False,
        ),
    ]
